# base microservice ami
---
- hosts: all
  vars:
    # set which role is consul server
    consul_servers_group: role=control
  roles:
    #- common
    #- consul

- hosts: role=control
  vars:
    consul_servers_group: role=control
    zookeeper_server_group: role=control
  roles:
    - exhibitor

- hosts: role=edge
  gather_facts: yes
  vars:
    traefik_package: v1.1.2
    # Set it to a domain you control (EG domain.com) 
    # and add a star domain to route traffic. (EG *.marathon.localhost)
    traefik_marathon_domain: marathon.domain
  roles:
    - traefik