# base microservice ami
---
- hosts: all
  vars:
    # set which role is consul server
    consul_servers_group: role=control
  roles:
    #- common
    #- consul

- hosts: role=control
  vars:
    consul_servers_group: role=control
    zookeeper_server_group: role=control
  roles:
    - exhibitor