# base microservice ami
---
- hosts: all
  vars:
    # set which role is consul server
    consul_servers_group: role=control
  roles:
    #- common
    #- consul

- hosts: role=control
  vars:
    consul_servers_group: role=control
    zookeeper_server_group: role=control
    mesos_mode: leader
  roles:
    #- exhibitor
    - mesos-docker
    - marathon-docker

- hosts: role=worker
  # role=worker hosts are a subset of "all". Since we already gathered facts on
  # all servers, we can skip it here to speed up the deployment.
  gather_facts: no
  vars:
    mesos_mode: follower
    zookeeper_server_group: role=control
  roles:
    - mesos-docker

- hosts: role=edge
  gather_facts: yes
  vars:
    traefik_package: v1.1.2
    # Set it to a domain you control (EG domain.com) 
    # and add a star domain to route traffic. (EG *.marathon.localhost)
    traefik_marathon_domain: marathon.domain
  roles:
    - traefik
