---
- name: restart consul
  become: yes
  command: /usr/local/bin/consul-rolling-restart.sh
  notify:
    - wait for consul to listen

- name: wait for consul to listen
  become: yes
  wait_for:
    port: 8500
