---
# handlers file for common
- name: start supervisord
  become: yes
  shell: "{{ supervisord_exec_dir }}/supervisord -c /etc/supervisord.conf"
  ignore_errors: true 
  register: start_supervisord
  notify: reload supervisord

- name: reload supervisord
  become: yes
  shell: "{{ supervisord_exec_dir }}/supervisorctl reload"
  when: start_supervisord|failed

- name: restart NetworkManager
  become: yes
  service:
    name: NetworkManager
    enabled: yes
    state: started
  tags:
    - dnsmasq

- name: restart dnsmasq
  become: yes
  service:
    name: dnsmasq
    enabled: yes
    state: started
  tags:
    - dnsmasq