---
- name: install system packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - build-essential 
  - python-dev 
  - python-pip
  - python3-pip 
  - bridge-utils 
  - ntp 
  - zip 
  - unzip 
  - curl
  - git
  - jq
  - openjdk-8-jdk
  - libzmq1
  - dnsmasq
  - network-manager
  when: ansible_os_family == 'Debian'
  tags:
    - common

- name: install system packages
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
  - epel-release  
  - python-pip
  - python3-pip
  - unzip 
  - curl
  - git
  - jq
  - java-1.8.0-openjdk
  - policycoreutils-python
  - libselinux-python
  when: ansible_os_family == 'RedHat'
  tags:
    - common

- name: install latest awscli boto docker_py
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
  - pip
  ignore_errors: True
  tags:
    - common

- include: ulimit.yml

- include: kernel.yml
  include: supervisord.yml
  include: docker.yml
  when: ansible_os_family == 'Debian'
