---
- name: install system packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - build-essential 
  - python-dev 
  - python-pip
  - python3-pip 
  - bridge-utils 
  - ntp 
  - zip 
  - unzip
  - curl
  - git
  - jq
  - openjdk-8-jdk
  - libzmq1
  - dnsmasq
  when: ansible_os_family == 'Debian'
  tags:
    - common

- name: install system packages
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
  - epel-release  
  - python-pip
  - python3-pip
  - nmap-ncat
  - unzip 
  - curl
  - git
  - jq
  - java-1.8.0-openjdk
  - policycoreutils-python
  - libselinux-python
  when: ansible_os_family == 'RedHat'
  tags:
    - common

- name: install latest awscli boto docker_py
  become: yes
  command: "/usr/bin/pip install awscli boto docker_py --upgrade"
  tags:
    - common

- include: ulimit.yml
- include: kernel.yml
- include: supervisord.yml
- include: docker.yml
- include: customize.yml


