---
- name: install supervisord
  become: yes
  shell: "/usr/bin/pip install supervisor=={{ supervisord_version }}"
  tags:
    - common

- name: setup supervisor service check script
  become: yes
  template:
    src: supervisor_service_check.sh.j2
    dest: "{{ customized_bin_dir }}/supervisor_service_check.sh"
    mode: 0755
  notify: restart consul
  tags:
    - consul

- name: ensuring required supervisord directories
  become: yes
  file: "path={{ supervisord_conf_dir }} state=directory"

- name: add supervisord config
  become: yes
  template: src=supervisord.conf.j2 dest=/etc/supervisord.conf
  notify:
    - start supervisord

- name: check supervisord running
  become: yes
  shell: "/usr/bin/pgrep supervisord"
  register: check_supervisord_running

- shell: echo "supervisord is not running"
  when: check_supervisord_running.stdout == ""
  notify:
    - start supervisord
