---
- name: ensure customized bin
  become: yes
  file:
    path: "{{ customized_bin_dir }}"
    state: directory
  tags:
    - exhibitor

- name: ensure zookeeper data dir
  become: yes
  file:
    path: "{{ zk_data_dir }}"
    state: directory
  tags:
    - exhibitor

- name: ensure zookeeper log dir
  become: yes
  file:
    path: "{{  zk_log_dir }}"
    state: directory
  tags:
    - exhibitor

- name: setup start_exhibitor script
  become: yes
  template:
    src: start_exhibitor.sh.j2
    dest: "{{ customized_bin_dir }}"/start_exhibitor.sh
    mode: 0755
  notify: restart exhibitor
  tags:
    - exhibitor

- name: setup exhibitor supervisord config
  become: yes
  template:
    src: exhibitor_supervisord.conf.j2
    dest: "{{ supervisord_conf_dir }}/exhibitor.conf"
  notify: restart exhibitor
  tags:
    - exhibitor

- name: start exhibitor supervisord
  become: yes
  supervisorctl: 
    name: exhibitor
    state: present
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"
  tags:
    - exhibitor

- name: setup consul service check exhibitor
  become: yes
  template:
    src: exhibitor_service.json.j2
    dest: /etc/consul.d/exhibitor_service.json
  #notify: reload consul config
  tags:
    - exhibitor
