---
- name: restart exhibitor
  become: yes
  supervisorctl: 
    name: exhibitor
    state: restarted
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"

- name: reload supervisor
  become: yes
  command: "{{ supervisord_exec_dir }}/supervisorctl reload"

- include: consul.yml
